// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 tommy0103 and contributors.

// Shared by scripts/export-abi.ts (writes) and test/abi-export.test.ts
// (checks the committed files), so both agree byte for byte.

export const EXPORTED_CONTRACTS = ["KeyRegistry", "ShareRegistry", "SkillRegistry", "UsageStats", "SkillMarket"] as const;

export function renderAbiJson(abi: unknown): string {
  return `${JSON.stringify(abi, null, 2)}\n`;
}

function exportName(contract: string): string {
  return `${contract[0]!.toLowerCase()}${contract.slice(1)}Abi`;
}

export function renderAbiIndex(abis: Record<string, unknown>): string {
  const lines = [
    "// Generated by scripts/export-abi.ts. Do not edit; run `npm run export-abi`.",
    "",
  ];
  for (const [name, abi] of Object.entries(abis)) {
    lines.push(`export const ${exportName(name)} = ${JSON.stringify(abi, null, 2)} as const;`, "");
  }
  return lines.join("\n");
}
